- id: pywsl
  name: pywsl
  description: Report blank-line violations in Python files
  entry: pywsl check --force-exclude
  language: python
  types_or: [python, pyi]
  require_serial: false

- id: pywsl-format
  name: pywsl-format
  description: Fix blank-line placement in Python files
  entry: pywsl format --force-exclude
  language: python
  types_or: [python, pyi]
  require_serial: false
